### ISSUE TITLE
General $HOME path for .env file for shared environments

### ISSUE THREAD

**Issue by weiannnnn** [bongosway/insomnia-plugin-dotenv#2]
I'm using Insomnia Teams to manage a shared environment and request library. We're using the `insomnia-plugin-dotenv`to manage secrets in our shared environments. 
 
![image](https://user-images.githubusercontent.com/33024408/106135733-38a4a100-6160-11eb-9756-d5472d0e11a5.png)
![image](https://user-images.githubusercontent.com/33024408/106135679-29bdee80-6160-11eb-9d1d-b9b4fc47eb6e.png)

However, this solution doesn't work for multiple users, as the path to the .env file resolves to _**my**_ specific location (i.e. User/_name_/file.env), which obviously is an invalid file path for anyone else.

----------------- 

All of us plan to save our .env files in the exact relative location (e.g. $HOME/Desktop/Insomnia/test.env).  Is it possible to update / make a new feature where the plugin resolves $HOME to the individual user?

Otherwise, does anyone know of a collaborative way to use this plugin, or manage store secrets in local .env files?

**Comment by bongosway** [comment]
Fixed by commit  6aec52a
Please kindly give it a spin and would be lovely to hear your feedback. 

Thanks.

**Comment by weiannnnn** [comment]
Hi @bongosway ! Thank you for responding so quickly, much appreciated.

I tried to get the version of the plugin (1.1.0) with this feature, and resorted to attempting to re-install it (deleted the folder from the plugins folder, and then downloaded from the hub), but I've come across this issue

![image](https://user-images.githubusercontent.com/33024408/106430768-2d08f100-6464-11eb-92f5-cab3da87b0d2.png)

Is anyone else experiencing this, and any advice on how to resolve? Would love to test out the functionality

**Comment by bongosway** [comment]
Hi @weiannnnn Issue is fixed now. Please give it a spin. thanks

**Comment by weiannnnn** [comment]
Hi @bongosway, apologies for the delay in reviewing this! 

Unfortunately this has not solved the issue we are facing, which is not being able to use dotenv in a shared workspace as the path to our dotenv files are different. As shown in the pic below, when someone sets up the path to their .env file in the environment, it throws an error for me.

<img width="572" alt="Screenshot 2021-04-07 at 08 55 57" src="https://user-images.githubusercontent.com/33024408/113831541-9fa58e00-977f-11eb-8803-91b4aee9eaf4.png">

Do you have any advice on how to properly implement dotenv for a shared workspace?
